# Generated by Django 3.2.2 on 2021-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_type',
            field=models.ManyToManyField(default='Inne', related_name='type', to='type.Type'),
        ),
    ]
