# Generated by Django 3.2.2 on 2021-05-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('product', '0003_auto_20210515_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='type.type'),
        ),
    ]
