# Generated by Django 3.2.2 on 2021-05-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('surename', models.CharField(blank=True, max_length=30)),
                ('isactive', models.BooleanField(default=True)),
                ('isstaff', models.BooleanField(default=False)),
                ('ismanager', models.BooleanField(default=False)),
                ('isadmin', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
