# Generated by Django 3.2.2 on 2021-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_power_flag',
            field=models.IntegerField(choices=[(0, 'Unactive'), (1, 'Employee'), (2, 'Manager'), (3, 'Admin')]),
        ),
    ]
