# Generated by Django 3.2.2 on 2021-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_u_power_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
