# Generated by Django 3.2.2 on 2021-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210916_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isonline',
            field=models.BooleanField(default=False),
        ),
    ]
