# Generated by Django 3.2.2 on 2021-05-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_store_products'),
        ('user', '0005_alter_user_u_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
