# Generated by Django 3.2.2 on 2021-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210513_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_isadmin',
            new_name='isadmin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_ismanager',
            new_name='ismanager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_isstaff',
            new_name='isstaff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_surename',
            new_name='surename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
