# Generated by Django 3.2.2 on 2021-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210513_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AlterField(
            model_name='user',
            name='surename',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
