# Generated by Django 3.2.2 on 2021-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210513_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surename',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
