# Generated by Django 3.2.2 on 2021-05-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_store_products'),
        ('user', '0012_alter_user_surename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
