# Generated by Django 3.2.2 on 2021-05-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
