# Generated by Django 3.2.2 on 2021-05-13 07:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_products',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200),
        ),
    ]
