# Generated by Django 3.2.2 on 2021-05-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_products',
        ),
    ]
