# Generated by Django 3.2.2 on 2021-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210515_1700'),
        ('store', '0002_remove_store_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
